### ISSUE TITLE
[Device Support] Razer Firefly V2

### ISSUE THREAD

**Issue by ACod00** [FruityRazer/FruityKit#17]
Is possible to add FireFly V2 and Lianli 011 Dynamic Razer Edition support?
Wave on Hutsman Elite is very very fast and on Viper Ultimate is very slow, is possible to add a slider for select speed of wave effect?

**Comment by edualm** [comment]
https://github.com/openrazer/openrazer/pull/1123 was merged so this can be implemented now.

**Comment by edualm** [comment]
There is support for this on `librazermacos`, should be trivial to implement.

**Comment by edualm** [comment]
Support has been added in `FruityUI` 1.5.
