### ISSUE TITLE
[Device Support] Razer Huntsman Mini

### ISSUE THREAD

**Issue by Schaefers** [FruityRazer/FruityKit#21]
Hi, would it be possible to add support for the Huntsman Mini? Would be nice to configure it in FruityUI.

**Comment by edualm** [comment]
Added a comment in https://github.com/1kc/librazermacos/issues/3, which when closed should add support on `FruityKit` too.

**Comment by edualm** [comment]
This was fixed some time ago but the issue was never closed.

The README needs updating which I'll try to do this week.
