### ISSUE TITLE
Razer Lancehead not detected

### ISSUE THREAD

**Issue by alexfry** [FruityRazer/FruityKit#3]
Hey

I'm using the prebuilt release binary under Catalina 10.15.4 with a Razer Lancehead.

Nothing is showing up in the sidebar.

![image](https://user-images.githubusercontent.com/900885/83206506-63cf8e80-a194-11ea-9ca3-dde3f277e9e3.png)

Let me know if there anything else I can test or probe.

**Comment by edualm** [comment]
Hello,

I've just released a beta version of FruityUI with **untested** support for this, as I don't own this device.

Could you give it a try?

https://github.com/FruityRazer/FruityUI/releases/tag/v1.2b1

Thanks!

**Comment by edualm** [comment]
Closing due to https://github.com/FruityRazer/FruityKit/issues/6.
