### ISSUE TITLE
Support for Razer Viper Ultimate Wireless

### ISSUE THREAD

**Issue by BenPicard** [FruityRazer/FruityKit#5]
Hi,

Any plan to add support for the Razer Viper Ultimate Wireless?

Regards,
Ben

**Comment by edualm** [comment]
Hello,

I've just released a beta version of FruityUI with **untested** support for this, as I don't own this device.

Could you give it a try?

https://github.com/FruityRazer/FruityUI/releases/tag/v1.2b1

Thanks!

**Comment by edualm** [comment]
Assuming this works due to the discussion over at https://github.com/FruityRazer/FruityKit/issues/6.
